version: '3'

volumes:
  db:

networks:
  polr:
  webproxy:
    external:
      name: webproxy
  web:
    external:
      name: web

services:

  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      # from env files
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - polr
  polr:
    image: mackmoe/polr_docker:latest
    restart: always
    environment:
      # Polr settings
      tld_or_ip: ${SERVICE_DOMAIN}
      # Evertramos Reverse Proxy Settings
      VIRTUAL_HOST: ${SERVICE_DOMAIN}
      LETSENCRYPT_HOST: ${SERVICE_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    depends_on:
      - db
    networks:
      - webproxy
      - web
      - polr # may be replaceable by `- default` network - check later
    labels:
      # Traefik Config
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${SERVICE_DOMAIN}" # multiple host-aliases with multiple host rules?
      - "traefik.port=9000"
      - "traefik.protocol=http"
